### ISSUE TITLE
Which DNS-Server is out of sync?

### ISSUE THREAD

**Issue by Farom** [bebehei/check_dnsserials#3]
When being informed by icinga/nagios about 1 of 4 DNS servers for a zone is out of sync, it would be a better startpoint to debug, if check_dnsserials could point to the server, that is out of sync.

**Comment by bebehei** [comment]
You can use `-v` (or `-vv`) for this. This is handy, if you want to test it manually.

But yeah, the output in production could be better. PR welcome :wink:

**Comment by Farom** [comment]
opened PR

**Comment by bebehei** [comment]
Released on icingaexchange: https://exchange.icinga.com/bebehei/check_dnsserials/releases

**Comment by bebehei** [comment]
Thanks for the PR. Incoming patches appreciated :+1:

**Comment by Farom** [comment]
This was fast.
