### ISSUE TITLE
Check always responds with OK

### ISSUE THREAD

**Issue by suniastar** [bebehei/check_dnsserials#7]
I'm using the current version 1.2 of the plugin.

Our setup consists of 2 DNS servers the fist one works as master syncing to a second DNS server.

When I run the command by myself with
```bash
/usr/lib/nagios/plugins/check_dnsserials -d example.domain -H ns1.domain-S ns2.domain -w 1
```
I always get the answer:
```bash
DNS OK, master serial: 2020103120, fails: 1, failed Servers: ns2.domain
```

I've already tired different combinations of arguments and numbers for `-c` and `-w` but I always get the same response with exit code 0.

**Comment by suniastar** [comment]
Also your README seems out of date:

FAILS is described by "The amount of DNS servers allowed having another serial" and the example list that `-w 2` should fail to warning state.

**Comment by bebehei** [comment]
https://github.com/bebehei/check_dnsserials/blob/8efd7bd9f8f0f8ca79623fb71ada55f2c3a3e550/check_dnsserials#L177-L183

Well having one failing server and using `-w 1` is OK. Either two servers have to fail, to make the plugin output critical or you have to use `-w 0`.

**Comment by bebehei** [comment]
It's an off by one error. And i've wrongly described it.

**Comment by bebehei** [comment]
Docs are fixed.  Thanks for pointing this out. I'll close the issue. If you think there is some other necessity to address this bug, just reopen it.

**Comment by suniastar** [comment]
But as I mentioned using `-w 0` also returns:

```
DNS OK, master serial: 2020103120, fails: 1, failed Servers: ns2.domain
```

**Comment by bebehei** [comment]
Could you give me the real test domain to debug it? I'm not using this plugin anymore and I do not have a test structure.

**Comment by suniastar** [comment]
I would rather not provide that detail but I figured out that it is possible to recreate the error with `1.1.1.1` and `1.0.0.1`.

```
root@dev-pc:~# /usr/lib/nagios/plugins/check_dnsserials -d teco.edu -H 1.1.1.1 -S 1.0.0.1 -w 0
DNS OK, master serial: 2020103128, fails: 1, failed Servers: 1.0.0.1
```

Does that help?

**Comment by bebehei** [comment]
```
[bebe:~/code/check_dnsserials] master(+8/-21) ± ./check_dnsserials -d teco.edu -H 1.1.1.1 -S 1.0.0.1 -w 0
DNS OK, master serial: 2020103128, fails: 0
[bebe:~/code/check_dnsserials] master(+8/-21) 3 ± ./check_dnsserials -d teco.edu -H 1.1.1.1 -S 1.0.0.1 -w 0
DNS OK, master serial: 2020103128, fails: 1, failed Servers: 1.0.0.1
```

Well, I guesss there is another problem, which changed in a recent dig version. I get different outputs. I'm not sure what changed.

I acknowledge this as a bug, but I won't take any extra steps to fix it. You have to fix it yourself, sorry.

**Comment by suniastar** [comment]
Thanks for your help. Once I found a fix I will create a push request ;)
